export interface SignCatalogEntry {
  id: string;
  name: string;
  glbUrl: string;
  category?: string;
}

export const SIGN_CATALOG: SignCatalogEntry[] = [
  {
    id: 'a',
    name: 'a',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/a.glb',
    category: 'Alphabet',
  },
  {
    id: 'b',
    name: 'b',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/b.glb',
    category: 'Alphabet',
  },
  {
    id: 'c',
    name: 'c',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/c.glb',
    category: 'Alphabet',
  },
  {
    id: 'd',
    name: 'd',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/d.glb',
    category: 'Alphabet',
  },
  {
    id: 'e',
    name: 'e',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/e.glb',
    category: 'Alphabet',
  },
  {
    id: 'f',
    name: 'f',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/f.glb',
    category: 'Alphabet',
  },
  {
    id: 'g',
    name: 'g',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/g.glb',
    category: 'Alphabet',
  },
  {
    id: 'h',
    name: 'h',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/h.glb',
    category: 'Alphabet',
  },
  {
    id: 'i',
    name: 'i',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/i.glb',
    category: 'Alphabet',
  },
  {
    id: 'j',
    name: 'j',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/j.glb',
    category: 'Alphabet',
  },
  {
    id: 'k',
    name: 'k',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/k.glb',
    category: 'Alphabet',
  },
  {
    id: 'l',
    name: 'l',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/l.glb',
    category: 'Alphabet',
  },
  {
    id: 'm',
    name: 'm',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/m.glb',
    category: 'Alphabet',
  },
  {
    id: 'n',
    name: 'n',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/n.glb',
    category: 'Alphabet',
  },
  {
    id: 'o',
    name: 'o',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/o.glb',
    category: 'Alphabet',
  },
  {
    id: 'p',
    name: 'p',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/p.glb',
    category: 'Alphabet',
  },
  {
    id: 'q',
    name: 'q',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/q.glb',
    category: 'Alphabet',
  },
  {
    id: 'r',
    name: 'r',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/r.glb',
    category: 'Alphabet',
  },
  {
    id: 's',
    name: 's',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/s.glb',
    category: 'Alphabet',
  },
  {
    id: 't',
    name: 't',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/t.glb',
    category: 'Alphabet',
  },
  {
    id: 'u',
    name: 'u',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/u.glb',
    category: 'Alphabet',
  },
  {
    id: 'v',
    name: 'v',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/v.glb',
    category: 'Alphabet',
  },
  {
    id: 'w',
    name: 'w',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/w.glb',
    category: 'Alphabet',
  },
  {
    id: 'x',
    name: 'x',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/x.glb',
    category: 'Alphabet',
  },
  {
    id: 'y',
    name: 'y',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/y.glb',
    category: 'Alphabet',
  },
  {
    id: 'z',
    name: 'z',
    glbUrl: 'https://storage.cloud.google.com/signlydaten/gebearde/Alphabet/z.glb',
    category: 'Alphabet',
  },
  {
    id: 'blau',
    name: 'blau',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Blau.glb',
    category: 'Farben',
  },
  {
    id: 'Dunkel',
    name: 'Dunkle',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Dunkel.glb',
    category: 'Farben',
  },
  {
    id: 'Gelb',
    name: 'Gelbe',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Gelb.glb',
    category: 'Farben',
  },
  {
    id: 'Hell',
    name: 'Hell',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Hell.glb',
    category: 'Farben',
  },
  {
    id: 'Orange',
    name: 'Orangene',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Orange.glb',
    category: 'Farben',
  },
  {
    id: 'Rot',
    name: 'Rote',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/Rot.glb',
    category: 'Farben',
  },
  {
    id: 'gruen',
    name: 'Grüne',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/gruen.glb',
    category: 'Farben',
  },
  {
    id: 'lila',
    name: 'Lila',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/lila.glb',
    category: 'Farben',
  },
  {
    id: 'pink',
    name: 'Pink',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Farben/pink.glb',
    category: 'Farben',
  },
  {
    id: 'Dorf',
    name: 'Dorf',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Dorf.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Dorf',
    name: 'Dorf',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Dorf.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Du',
    name: 'Du',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Du.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Er Sie Es',
    name: 'Er Sie Es',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Er:Sie:Es.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Hallo',
    name: 'Hallo',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Hallo.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Ich',
    name: 'Ich',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Ich.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Mein',
    name: 'Mein',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Mein.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Name',
    name: 'Name',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Name.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Stadt',
    name: 'Stadt',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Stadt.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Tschuess',
    name: 'Tschüss',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Tschuess.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Wie',
    name: 'Wie',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Wie.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Wohnen',
    name: 'Wohnen',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/Wohnen.glb',
    category: 'Vorstellen',
  },

  {
    id: 'Wie_alt',
    name: 'Wie alt',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/wie_alt.glb',
    category: 'Vorstellen',
  },
  {
    id: 'Wie Gehts',
    name: 'Wie Gehts',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Vorstellen/wie_gehts.glb',
    category: 'Vorstellen',
  },

    {
    id: '1',
    name: '1',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/1.glb',
    category: 'Zahlen',
  },
      {
    id: '2',
    name: '2',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/2.glb',
    category: 'Zahlen',
  },
      {
    id: '3',
    name: '3',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/3.glb',
    category: 'Zahlen',
  },
      {
    id: '4',
    name: '4',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/4.glb',
    category: 'Zahlen',
  },
      {
    id: '5',
    name: '5',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/5.glb',
    category: 'Zahlen',
  },
      {
    id: '6',
    name: '6',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/6.glb',
    category: 'Zahlen',
  },
      {
    id: '7',
    name: '7',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/7.glb',
    category: 'Zahlen',
  },
      {
    id: '8',
    name: '8',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/8.glb',
    category: 'Zahlen',
  },
      {
    id: '9',
    name: '9',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/9.glb',
    category: 'Zahlen',
  },
      {
    id: '6767',
    name: '6767',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/zahlen/6767.glb',
    category: 'Zahlen',
  },
        {
    id: 'Früh',
    name: 'Früh',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Fr%C3%BCh.glb',
    category: 'Zeit',
  },
          {
    id: 'Gestern',
    name: 'Gestern',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Gestern.glb',
    category: 'Zeit',
  },
          {
    id: 'Heute',
    name: 'Heute',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Heute.glb',
    category: 'Zeit',
  },
            {
    id: 'Jetzt',
    name: 'Jetzt',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Jetzt.glb',
    category: 'Zeit',
  },
            {
    id: 'Morgen',
    name: 'Morgen',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Morgen.glb',
    category: 'Zeit',
  },
            {
    id: 'Später',
    name: 'Später',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Später.glb',
    category: 'Zeit',
  },
            {
    id: 'Spät',
    name: 'Spät',
    glbUrl: 'https://storage.googleapis.com/signlydaten/gebearde/Zeit/Spät.glb',
    category: 'Zeit',
  },
];
